<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            // Fiction (category_id:1) - Total 7 Buku
            [
                'name' => 'The Little Prince',
                'price' => 150000,
                'stock' => 25,
                'description' => 'Cerita klasik seorang pangeran kecil menjelajah alam.',
                'author' => 'Antoine de Saint-Exupéry',
                'publisher' => 'Reynal & Hitchcock',
                'year' => 1943,
                'isbn' => '9780156012195',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1367545443i/157993.jpg', 
            ],
            [
                'name' => 'Laskar Pelangi',
                'price' => 85000,
                'stock' => 30,
                'description' => 'Perjuangan anak-anak Belitung mengejar pendidikan.',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'year' => 2005,
                'isbn' => '9789793062794',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/laskarpelangi/400/600',
            ],
            [
                'name' => 'To Kill a Mockingbird',
                'price' => 99000,
                'stock' => 28,
                'description' => 'Klasik tentang keadilan dan moral di Selatan Amerika.',
                'author' => 'Harper Lee',
                'publisher' => 'J.B. Lippincott & Co.',
                'year' => 1960,
                'isbn' => '9780061120084',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/mockingbirdbook/400/600',
            ],
            [
                'name' => '1984',
                'price' => 88000,
                'stock' => 34,
                'description' => 'Dystopia totalitarian pengawasan penuh.',
                'author' => 'George Orwell',
                'publisher' => 'Secker & Warburg',
                'year' => 1949,
                'isbn' => '9780451524935',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/orwell1984/400/600',
            ],
            [
                'name' => 'The Hobbit',
                'price' => 110000,
                'stock' => 22,
                'description' => 'Petualangan Bilbo Baggins sebelum Lord of the Rings.',
                'author' => 'J.R.R. Tolkien',
                'publisher' => 'George Allen & Unwin',
                'year' => 1937,
                'isbn' => '9780547928227',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/thehobbit/400/600',
            ],
            [ // Buku Baru 1
                'name' => 'Harry Potter and the Sorcerer\'s Stone',
                'price' => 175000,
                'stock' => 30,
                'description' => 'Awal kisah petualangan penyihir muda Harry Potter.',
                'author' => 'J.K. Rowling',
                'publisher' => 'Bloomsbury Publishing',
                'year' => 1997,
                'isbn' => '9780747532743',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/harrypotter1/400/600',
            ],
            [ // Buku Baru 2
                'name' => 'The Da Vinci Code',
                'price' => 130000,
                'stock' => 20,
                'description' => 'Thriller misteri yang melibatkan simbol rahasia dan sejarah agama.',
                'author' => 'Dan Brown',
                'publisher' => 'Doubleday',
                'year' => 2003,
                'isbn' => '9780385504201',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/davincicode/400/600',
            ],

            // Non-Fiction (category_id:2) - Total 7 Buku
            [
                'name' => 'Sapiens',
                'price' => 180000,
                'stock' => 20,
                'description' => 'Sejarah singkat umat manusia.',
                'author' => 'Yuval Noah Harari',
                'publisher' => 'Harper',
                'year' => 2014,
                'isbn' => '9780062316097',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/sapiensbook/400/600',
            ],
            [
                'name' => 'Atomic Habits',
                'price' => 165000,
                'stock' => 35,
                'description' => 'Membentuk kebiasaan baik & hilangkan kebiasaan buruk.',
                'author' => 'James Clear',
                'publisher' => 'Avery',
                'year' => 2018,
                'isbn' => '9780735211292',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1655988385i/40121378.jpg',
            ],
            [
                'name' => 'Educated',
                'price' => 135000,
                'stock' => 18,
                'description' => 'Memoar perjalanan dari keluarga survivalist ke akademis.',
                'author' => 'Tara Westover',
                'publisher' => 'Random House',
                'year' => 2018,
                'isbn' => '9780399590504',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/educatedbook/400/600',
            ],
            [
                'name' => 'Thinking, Fast and Slow',
                'price' => 150000,
                'stock' => 26,
                'description' => 'Dua sistem berpikir: cepat intuitif dan lambat analitis.',
                'author' => 'Daniel Kahneman',
                'publisher' => 'Farrar, Straus and Giroux',
                'year' => 2011,
                'isbn' => '9780374533557',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/fastslowbook/400/600',
            ],
            [
                'name' => 'Deep Work',
                'price' => 125000,
                'stock' => 30,
                'description' => 'Strategi fokus mendalam untuk hasil maksimal.',
                'author' => 'Cal Newport',
                'publisher' => 'Grand Central Publishing',
                'year' => 2016,
                'isbn' => '9781455586691',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/deepworkbook/400/600',
            ],
            [ // Buku Baru 1
                'name' => 'The Power of Now',
                'price' => 115000,
                'stock' => 25,
                'description' => 'Panduan untuk hidup di masa kini dan menemukan kedamaian.',
                'author' => 'Eckhart Tolle',
                'publisher' => 'New World Library',
                'year' => 1997,
                'isbn' => '9781577314806',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/powerofnow/400/600',
            ],
            [ // Buku Baru 2
                'name' => 'Ngenest',
                'price' => 95000,
                'stock' => 15,
                'description' => 'Ngetawain hidup ala Ernest.',
                'author' => 'Ernest Prakasa',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2013,
                'isbn' => '9786021755976',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/ernestautobiography/400/600',
            ],

            // Comic & Manga (category_id:3) - Total 5 Buku
            [
                'name' => 'One Piece Vol. 1',
                'price' => 45000,
                'stock' => 50,
                'description' => 'Awal petualangan Luffy mencari One Piece.',
                'author' => 'Eiichiro Oda',
                'publisher' => 'Shueisha',
                'year' => 1997,
                'isbn' => '9784088725095',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/onepiecemanga/400/600',
            ],
            [
                'name' => 'Naruto Vol. 1',
                'price' => 42000,
                'stock' => 40,
                'description' => 'Perjalanan ninja muda Naruto.',
                'author' => 'Masashi Kishimoto',
                'publisher' => 'Shueisha',
                'year' => 1999,
                'isbn' => '9784088730226',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/narutomanga/400/600',
            ],
            [
                'name' => 'Demon Slayer Vol. 1',
                'price' => 52000,
                'stock' => 38,
                'description' => 'Awal perjalanan Tanjiro melawan iblis.',
                'author' => 'Koyoharu Gotouge',
                'publisher' => 'Shueisha',
                'year' => 2016,
                'isbn' => '9781974700523',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/demonslayer/400/600',
            ],
            [
                'name' => 'Chainsaw Man Vol. 1',
                'price' => 54000,
                'stock' => 32,
                'description' => 'Denji bergabung dengan pemburu iblis pemerintah.',
                'author' => 'Tatsuki Fujimoto',
                'publisher' => 'Shueisha',
                'year' => 2019,
                'isbn' => '9781974709939',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/chainsawman/400/600',
            ],
            [
                'name' => 'Spy x Family Vol. 1',
                'price' => 56000,
                'stock' => 29,
                'description' => 'Keluarga pura-pura penuh rahasia unik.',
                'author' => 'Tatsuya Endo',
                'publisher' => 'Shueisha',
                'year' => 2020,
                'isbn' => '9781974715466',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/spyxfamily/400/600',
            ],
            
            // Teen Reading (category_id:4) - Total 5 Buku
            [
                'name' => 'The Hunger Games',
                'price' => 120000,
                'stock' => 27,
                'description' => 'Pertarungan hidup dan kemerdekaan di Capitol.',
                'author' => 'Suzanne Collins',
                'publisher' => 'Scholastic',
                'year' => 2008,
                'isbn' => '9780439023528',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/hungergamesbook/400/600',
            ],
            [
                'name' => 'Divergent',
                'price' => 98000,
                'stock' => 24,
                'description' => 'Fraksi dan identitas dalam masyarakat terpecah.',
                'author' => 'Veronica Roth',
                'publisher' => 'Katherine Tegen Books',
                'year' => 2011,
                'isbn' => '9780062024039',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/divergentbook/400/600',
            ],
            [
                'name' => 'The Maze Runner',
                'price' => 97000,
                'stock' => 31,
                'description' => 'Remaja terjebak dalam labirin misterius.',
                'author' => 'James Dashner',
                'publisher' => 'Delacorte Press',
                'year' => 2009,
                'isbn' => '9780385737951',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/mazerunnerbook/400/600',
            ],
            [ // Buku Baru 1
                'name' => 'Percy Jackson & The Lightning Thief',
                'price' => 115000,
                'stock' => 28,
                'description' => 'Petualangan Percy Jackson menemukan petir Zeus yang hilang.',
                'author' => 'Rick Riordan',
                'publisher' => 'Disney Hyperion',
                'year' => 2005,
                'isbn' => '9780786856299',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/percyjackson1/400/600',
            ],
            [ // Buku Baru 2
                'name' => 'The Fault in Our Stars',
                'price' => 105000,
                'stock' => 25,
                'description' => 'Kisah cinta remaja yang menyentuh di tengah penyakit.',
                'author' => 'John Green',
                'publisher' => 'Dutton Books',
                'year' => 2012,
                'isbn' => '9780525478812',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/faultinourstars/400/600',
            ],
            
            // Self-Help (category_id:5) - Total 6 Buku
            [
                'name' => 'The Subtle Art of Not Giving a F*ck',
                'price' => 140000,
                'stock' => 33,
                'description' => 'Prioritaskan hal penting dalam hidup.',
                'author' => 'Mark Manson',
                'publisher' => 'HarperOne',
                'year' => 2016,
                'isbn' => '9780062457714',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/subtleartbook/400/600',
            ],
            [
                'name' => 'The Power of Habit',
                'price' => 132000,
                'stock' => 29,
                'description' => 'Bagaimana kebiasaan bekerja dan diubah.',
                'author' => 'Charles Duhigg',
                'publisher' => 'Random House',
                'year' => 2012,
                'isbn' => '9780812981605',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/powerofhabitbook/400/600',
            ],
            [
                'name' => 'Can\'t Hurt Me',
                'price' => 155000,
                'stock' => 21,
                'description' => 'Mental toughness dan disiplin radikal.',
                'author' => 'David Goggins',
                'publisher' => 'Lioncrest Publishing',
                'year' => 2018,
                'isbn' => '9781544512273',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/canthurtmebook/400/600',
            ],
            [ // Buku Baru 1
                'name' => 'Dare to Lead',
                'price' => 145000,
                'stock' => 24,
                'description' => 'Belajar memimpin dengan keberanian, empati, dan koneksi.',
                'author' => 'Brené Brown',
                'publisher' => 'Random House',
                'year' => 2018,
                'isbn' => '9780399592522',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/daretolead/400/600',
            ],
            [ // Buku Baru 2
                'name' => 'Filosofi Teras',
                'price' => 95000,
                'stock' => 35,
                'description' => 'Panduan praktis filosofi Stoa untuk mengatasi emosi negatif.',
                'author' => 'Henry Manampiring',
                'publisher' => 'Kompas',
                'year' => 2018,
                'isbn' => '9786024125189',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/filosofiteras/400/600',
            ],
            [ // Buku Baru 3
                'name' => 'Start With Why',
                'price' => 160000,
                'stock' => 20,
                'description' => 'Bagaimana pemimpin hebat menginspirasi tindakan.',
                'author' => 'Simon Sinek',
                'publisher' => 'Portfolio',
                'year' => 2009,
                'isbn' => '9781591846444',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/startwithwhy/400/600',
            ],

            // Technology (category_id:6) - Total 5 Buku
            [
                'name' => 'Clean Architecture',
                'price' => 230000,
                'stock' => 20,
                'description' => 'Struktur arsitektur perangkat lunak yang maintainable.',
                'author' => 'Robert C. Martin',
                'publisher' => 'Prentice Hall',
                'year' => 2017,
                'isbn' => '9780134494166',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/cleanarchitecturebook/400/600',
            ],
            [
                'name' => 'Designing Data-Intensive Applications',
                'price' => 350000,
                'stock' => 15,
                'description' => 'Fundamental sistem data modern skala besar.',
                'author' => 'Martin Kleppmann',
                'publisher' => 'O\'Reilly Media',
                'year' => 2017,
                'isbn' => '9781449373320',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/ddiabook/400/600',
            ],
            [
                'name' => 'Refactoring',
                'price' => 275000,
                'stock' => 19,
                'description' => 'Pola peningkatan kualitas kode tanpa mengubah perilaku.',
                'author' => 'Martin Fowler',
                'publisher' => 'Addison-Wesley',
                'year' => 2018,
                'isbn' => '9780134757599',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/refactoringbook/400/600',
            ],
            [ // Buku Baru 1
                'name' => 'The Mythical Man-Month',
                'price' => 190000,
                'stock' => 17,
                'description' => 'Esai tentang rekayasa perangkat lunak.',
                'author' => 'Frederick Brooks Jr.',
                'publisher' => 'Addison-Wesley',
                'year' => 1975,
                'isbn' => '9780201835953',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/mythicalmanmonth/400/600',
            ],
            [ // Buku Baru 2
                'name' => 'Code Complete',
                'price' => 320000,
                'stock' => 14,
                'description' => 'Panduan komprehensif untuk konstruksi perangkat lunak.',
                'author' => 'Steve McConnell',
                'publisher' => 'Microsoft Press',
                'year' => 2004,
                'isbn' => '9780735619678',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/codecomplete/400/600',
            ],

            // Fiction Additional Books (15 more books)
            [
                'name' => 'Pride and Prejudice',
                'price' => 89000,
                'stock' => 25,
                'description' => 'Klasik romantis Jane Austen tentang Elizabeth Bennet.',
                'author' => 'Jane Austen',
                'publisher' => 'T. Egerton',
                'year' => 1813,
                'isbn' => '9780141439518',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/prideandprejudice/400/600',
            ],
            [
                'name' => 'The Great Gatsby',
                'price' => 78000,
                'stock' => 30,
                'description' => 'Kemewahan dan tragedi era Jazz Amerika.',
                'author' => 'F. Scott Fitzgerald',
                'publisher' => 'Scribner',
                'year' => 1925,
                'isbn' => '9780743273565',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/greatgatsby/400/600',
            ],
            [
                'name' => 'Jane Eyre',
                'price' => 92000,
                'stock' => 22,
                'description' => 'Kisah yatim piatu yang menjadi governess.',
                'author' => 'Charlotte Brontë',
                'publisher' => 'Smith, Elder & Co.',
                'year' => 1847,
                'isbn' => '9780141441146',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/janeeyre/400/600',
            ],
            [
                'name' => 'Lord of the Flies',
                'price' => 76000,
                'stock' => 28,
                'description' => 'Anak-anak terdampar di pulau tak berpenghuni.',
                'author' => 'William Golding',
                'publisher' => 'Faber & Faber',
                'year' => 1954,
                'isbn' => '9780571056866',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/lordofflies/400/600',
            ],
            [
                'name' => 'Brave New World',
                'price' => 95000,
                'stock' => 21,
                'description' => 'Dystopia futuristik Aldous Huxley.',
                'author' => 'Aldous Huxley',
                'publisher' => 'Chatto & Windus',
                'year' => 1932,
                'isbn' => '9780060850524',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/bravenewworld/400/600',
            ],
            [
                'name' => 'The Catcher in the Rye',
                'price' => 87000,
                'stock' => 26,
                'description' => 'Perjalanan remaja Holden Caulfield di New York.',
                'author' => 'J.D. Salinger',
                'publisher' => 'Little, Brown and Company',
                'year' => 1951,
                'isbn' => '9780316769174',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/catcherintherye/400/600',
            ],
            [
                'name' => 'Wuthering Heights',
                'price' => 84000,
                'stock' => 19,
                'description' => 'Kisah cinta tragis di Yorkshire moors.',
                'author' => 'Emily Brontë',
                'publisher' => 'Thomas Cautley Newby',
                'year' => 1847,
                'isbn' => '9780141439556',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/wutheringheights/400/600',
            ],
            [
                'name' => 'One Hundred Years of Solitude',
                'price' => 118000,
                'stock' => 17,
                'description' => 'Realisme magis keluarga Buendía.',
                'author' => 'Gabriel García Márquez',
                'publisher' => 'Harper & Row',
                'year' => 1967,
                'isbn' => '9780060883287',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/hundredyearssolitude/400/600',
            ],
            [
                'name' => 'Fahrenheit 451',
                'price' => 81000,
                'stock' => 33,
                'description' => 'Dunia masa depan di mana buku dibakar.',
                'author' => 'Ray Bradbury',
                'publisher' => 'Ballantine Books',
                'year' => 1953,
                'isbn' => '9781451673319',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/fahrenheit451/400/600',
            ],
            [
                'name' => 'Animal Farm',
                'price' => 72000,
                'stock' => 38,
                'description' => 'Alegori politik tentang revolusi hewan.',
                'author' => 'George Orwell',
                'publisher' => 'Secker & Warburg',
                'year' => 1945,
                'isbn' => '9780452284241',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/animalfarm/400/600',
            ],
            [
                'name' => 'The Lord of the Rings: Fellowship',
                'price' => 145000,
                'stock' => 15,
                'description' => 'Awal perjalanan epic Frodo dan cincin.',
                'author' => 'J.R.R. Tolkien',
                'publisher' => 'George Allen & Unwin',
                'year' => 1954,
                'isbn' => '9780547928210',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/fellowshipring/400/600',
            ],
            [
                'name' => 'Moby Dick',
                'price' => 108000,
                'stock' => 14,
                'description' => 'Obsesi Kapten Ahab mengejar paus putih.',
                'author' => 'Herman Melville',
                'publisher' => 'Harper & Brothers',
                'year' => 1851,
                'isbn' => '9780142437247',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/mobydick/400/600',
            ],
            [
                'name' => 'Dune',
                'price' => 125000,
                'stock' => 23,
                'description' => 'Epic sci-fi di planet gurun Arrakis.',
                'author' => 'Frank Herbert',
                'publisher' => 'Chilton Books',
                'year' => 1965,
                'isbn' => '9780441172719',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/dunenovel/400/600',
            ],
            [
                'name' => 'The Chronicles of Narnia',
                'price' => 135000,
                'stock' => 20,
                'description' => 'Petualangan magis di dunia Narnia.',
                'author' => 'C.S. Lewis',
                'publisher' => 'Geoffrey Bles',
                'year' => 1950,
                'isbn' => '9780066238500',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/chroniclesnarnia/400/600',
            ],
            [
                'name' => 'Bumi Manusia',
                'price' => 95000,
                'stock' => 27,
                'description' => 'Novel sejarah Indonesia karya Pramoedya.',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'year' => 1980,
                'isbn' => '9789799731408',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/bumimanusia/400/600',
            ],

            // Non-Fiction Additional Books (15 more books)
            [
                'name' => 'The Lean Startup',
                'price' => 145000,
                'stock' => 25,
                'description' => 'Metodologi startup untuk inovasi berkelanjutan.',
                'author' => 'Eric Ries',
                'publisher' => 'Crown Business',
                'year' => 2011,
                'isbn' => '9780307887894',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/leanstartup/400/600',
            ],
            [
                'name' => 'Zero to One',
                'price' => 155000,
                'stock' => 22,
                'description' => 'Notes on startups dan cara membangun masa depan.',
                'author' => 'Peter Thiel',
                'publisher' => 'Crown Business',
                'year' => 2014,
                'isbn' => '9780804139298',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/zerotoone/400/600',
            ],
            [
                'name' => 'Good to Great',
                'price' => 168000,
                'stock' => 19,
                'description' => 'Mengapa beberapa perusahaan membuat lompatan.',
                'author' => 'Jim Collins',
                'publisher' => 'HarperBusiness',
                'year' => 2001,
                'isbn' => '9780066620992',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/goodtogreat/400/600',
            ],
            [
                'name' => 'The 7 Habits of Highly Effective People',
                'price' => 142000,
                'stock' => 31,
                'description' => 'Prinsip-prinsip untuk efektivitas pribadi dan interpersonal.',
                'author' => 'Stephen R. Covey',
                'publisher' => 'Free Press',
                'year' => 1989,
                'isbn' => '9780743269513',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/7habits/400/600',
            ],
            [
                'name' => 'Outliers',
                'price' => 128000,
                'stock' => 26,
                'description' => 'Cerita kesuksesan dan faktor-faktor tersembunyi.',
                'author' => 'Malcolm Gladwell',
                'publisher' => 'Little, Brown and Company',
                'year' => 2008,
                'isbn' => '9780316017930',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/outliers/400/600',
            ],
            [
                'name' => 'The Tipping Point',
                'price' => 118000,
                'stock' => 28,
                'description' => 'Bagaimana perubahan kecil membuat perbedaan besar.',
                'author' => 'Malcolm Gladwell',
                'publisher' => 'Little, Brown and Company',
                'year' => 2000,
                'isbn' => '9780316346627',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/tippingpoint/400/600',
            ],
            [
                'name' => 'Blink',
                'price' => 115000,
                'stock' => 24,
                'description' => 'Kekuatan berpikir tanpa berpikir.',
                'author' => 'Malcolm Gladwell',
                'publisher' => 'Little, Brown and Company',
                'year' => 2005,
                'isbn' => '9780316172324',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/blinkbook/400/600',
            ],
            [
                'name' => 'The Art of War',
                'price' => 89000,
                'stock' => 35,
                'description' => 'Strategi militer klasik Sun Tzu.',
                'author' => 'Sun Tzu',
                'publisher' => 'Various',
                'year' => -500, // Original year
                'isbn' => '9781599869773',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/artofwar/400/600',
            ],
            [
                'name' => 'Freakonomics',
                'price' => 135000,
                'stock' => 21,
                'description' => 'Sisi tersembunyi dari segala hal.',
                'author' => 'Steven Levitt & Stephen Dubner',
                'publisher' => 'William Morrow',
                'year' => 2005,
                'isbn' => '9780060731328',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/freakonomics/400/600',
            ],
            [
                'name' => 'The Black Swan',
                'price' => 158000,
                'stock' => 18,
                'description' => 'Dampak peristiwa yang sangat tidak mungkin.',
                'author' => 'Nassim Nicholas Taleb',
                'publisher' => 'Random House',
                'year' => 2007,
                'isbn' => '9781400063512',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/blackswan/400/600',
            ],
            [
                'name' => 'Mindset',
                'price' => 142000,
                'stock' => 29,
                'description' => 'Psikologi sukses: fixed vs growth mindset.',
                'author' => 'Carol S. Dweck',
                'publisher' => 'Random House',
                'year' => 2006,
                'isbn' => '9781400062751',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/mindsetbook/400/600',
            ],
            [
                'name' => 'The 4-Hour Workweek',
                'price' => 148000,
                'stock' => 23,
                'description' => 'Escape 9-5, live anywhere, dan join the new rich.',
                'author' => 'Timothy Ferriss',
                'publisher' => 'Crown Publishers',
                'year' => 2007,
                'isbn' => '9780307353139',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/4hourworkweek/400/600',
            ],
            [
                'name' => 'The Immortal Life of Henrietta Lacks',
                'price' => 152000,
                'stock' => 17,
                'description' => 'Kisah nyata sel HeLa yang mengubah sains.',
                'author' => 'Rebecca Skloot',
                'publisher' => 'Crown Publishers',
                'year' => 2010,
                'isbn' => '9781400052189',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/henriettalacks/400/600',
            ],
            [
                'name' => 'Into the Wild',
                'price' => 125000,
                'stock' => 22,
                'description' => 'Kisah nyata Christopher McCandless di Alaska.',
                'author' => 'Jon Krakauer',
                'publisher' => 'Villard',
                'year' => 1996,
                'isbn' => '9780679428503',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/intothewild/400/600',
            ],
            [
                'name' => 'A Brief History of Time',
                'price' => 165000,
                'stock' => 16,
                'description' => 'Penjelasan kosmologi untuk pembaca awam.',
                'author' => 'Stephen Hawking',
                'publisher' => 'Bantam Dell Publishing Group',
                'year' => 1988,
                'isbn' => '9780553380163',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/briefhistorytime/400/600',
            ],

            // Comic & Manga Additional Books (15 more books)
            [
                'name' => 'Attack on Titan Vol. 1',
                'price' => 58000,
                'stock' => 42,
                'description' => 'Manusia vs Titan raksasa.',
                'author' => 'Hajime Isayama',
                'publisher' => 'Kodansha',
                'year' => 2009,
                'isbn' => '9781612620244',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/attackontitan/400/600',
            ],
            [
                'name' => 'Death Note Vol. 1',
                'price' => 48000,
                'stock' => 35,
                'description' => 'Buku catatan kematian Light Yagami.',
                'author' => 'Tsugumi Ohba',
                'publisher' => 'Shueisha',
                'year' => 2003,
                'isbn' => '9781421501680',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/deathnote/400/600',
            ],
            [
                'name' => 'Tokyo Ghoul Vol. 1',
                'price' => 52000,
                'stock' => 28,
                'description' => 'Kaneki berubah menjadi ghoul.',
                'author' => 'Sui Ishida',
                'publisher' => 'Shueisha',
                'year' => 2011,
                'isbn' => '9781421580364',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/tokyoghoul/400/600',
            ],
            [
                'name' => 'My Hero Academia Vol. 1',
                'price' => 46000,
                'stock' => 45,
                'description' => 'Deku mengejar mimpi jadi superhero.',
                'author' => 'Kohei Horikoshi',
                'publisher' => 'Shueisha',
                'year' => 2014,
                'isbn' => '9781421582696',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/myheroacademia/400/600',
            ],
            [
                'name' => 'Dragon Ball Vol. 1',
                'price' => 44000,
                'stock' => 38,
                'description' => 'Petualangan Goku mencari Dragon Ball.',
                'author' => 'Akira Toriyama',
                'publisher' => 'Shueisha',
                'year' => 1984,
                'isbn' => '9781569319307',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/dragonball/400/600',
            ],
            [
                'name' => 'Fullmetal Alchemist Vol. 1',
                'price' => 50000,
                'stock' => 33,
                'description' => 'Saudara Elric dan equivalent exchange.',
                'author' => 'Hiromu Arakawa',
                'publisher' => 'Square Enix',
                'year' => 2001,
                'isbn' => '9781591169208',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/fullmetalalchemist/400/600',
            ],
            [
                'name' => 'Bleach Vol. 1',
                'price' => 47000,
                'stock' => 31,
                'description' => 'Ichigo jadi Soul Reaper.',
                'author' => 'Tite Kubo',
                'publisher' => 'Shueisha',
                'year' => 2001,
                'isbn' => '9781591164203',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/bleachmanga/400/600',
            ],
            [
                'name' => 'Hunter x Hunter Vol. 1',
                'price' => 49000,
                'stock' => 26,
                'description' => 'Gon mencari ayahnya yang Hunter.',
                'author' => 'Yoshihiro Togashi',
                'publisher' => 'Shueisha',
                'year' => 1998,
                'isbn' => '9781591167532',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/hunterxhunter/400/600',
            ],
            [
                'name' => 'Jujutsu Kaisen Vol. 1',
                'price' => 53000,
                'stock' => 39,
                'description' => 'Yuji melawan kutukan dengan jujutsu.',
                'author' => 'Gege Akutami',
                'publisher' => 'Shueisha',
                'year' => 2018,
                'isbn' => '9781974710027',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/jujutsukaisen/400/600',
            ],
            [
                'name' => 'One Punch Man Vol. 1',
                'price' => 45000,
                'stock' => 44,
                'description' => 'Saitama hero yang terlalu kuat.',
                'author' => 'ONE',
                'publisher' => 'Shogakukan',
                'year' => 2012,
                'isbn' => '9781421585642',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/onepunchman/400/600',
            ],
            [
                'name' => 'Mob Psycho 100 Vol. 1',
                'price' => 48000,
                'stock' => 27,
                'description' => 'Mob dan kekuatan psikisnya.',
                'author' => 'ONE',
                'publisher' => 'Shogakukan',
                'year' => 2012,
                'isbn' => '9781506706344',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/mobpsycho100/400/600',
            ],
            [
                'name' => 'Fairy Tail Vol. 1',
                'price' => 46000,
                'stock' => 32,
                'description' => 'Guild wizard Natsu dan Happy.',
                'author' => 'Hiro Mashima',
                'publisher' => 'Kodansha',
                'year' => 2006,
                'isbn' => '9781612622767',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/fairytail/400/600',
            ],
            [
                'name' => 'Seven Deadly Sins Vol. 1',
                'price' => 51000,
                'stock' => 29,
                'description' => 'Meliodas dan tujuh dosa mematikan.',
                'author' => 'Nakaba Suzuki',
                'publisher' => 'Kodansha',
                'year' => 2012,
                'isbn' => '9781612629216',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/sevendeadlysins/400/600',
            ],
            [
                'name' => 'Black Clover Vol. 1',
                'price' => 47000,
                'stock' => 36,
                'description' => 'Asta tanpa magic di dunia sihir.',
                'author' => 'Yūki Tabata',
                'publisher' => 'Shueisha',
                'year' => 2015,
                'isbn' => '9781421590158',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/blackclover/400/600',
            ],
            [
                'name' => 'The Promised Neverland Vol. 1',
                'price' => 54000,
                'stock' => 25,
                'description' => 'Anak-anak melarikan diri dari panti asuhan.',
                'author' => 'Kaiu Shirai',
                'publisher' => 'Shueisha',
                'year' => 2016,
                'isbn' => '9781421597126',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/promisedneverland/400/600',
            ],

            // Teen Reading Additional Books (10 more books)
            [
                'name' => 'Twilight',
                'price' => 95000,
                'stock' => 32,
                'description' => 'Cinta Bella dan Edward vampire.',
                'author' => 'Stephenie Meyer',
                'publisher' => 'Little, Brown and Company',
                'year' => 2005,
                'isbn' => '9780316015844',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/twilightbook/400/600',
            ],
            [
                'name' => 'The Outsiders',
                'price' => 78000,
                'stock' => 29,
                'description' => 'Konflik antar gang remaja tahun 1960an.',
                'author' => 'S.E. Hinton',
                'publisher' => 'Viking Press',
                'year' => 1967,
                'isbn' => '9780140385724',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/outsiders/400/600',
            ],
            [
                'name' => 'Thirteen Reasons Why',
                'price' => 89000,
                'stock' => 26,
                'description' => 'Hannah Baker dan 13 alasan bunuh diri.',
                'author' => 'Jay Asher',
                'publisher' => 'RazorBill',
                'year' => 2007,
                'isbn' => '9781595141712',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/thirteenreasons/400/600',
            ],
            [
                'name' => 'Eleanor & Park',
                'price' => 82000,
                'stock' => 24,
                'description' => 'Kisah cinta pertama dua outsider.',
                'author' => 'Rainbow Rowell',
                'publisher' => 'St. Martin\'s Press',
                'year' => 2013,
                'isbn' => '9781250012579',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/eleanorpark/400/600',
            ],
            [
                'name' => 'Wonder',
                'price' => 85000,
                'stock' => 35,
                'description' => 'Auggie dengan kelainan wajah masuk sekolah.',
                'author' => 'R.J. Palacio',
                'publisher' => 'Knopf Books',
                'year' => 2012,
                'isbn' => '9780375869020',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/wonderbook/400/600',
            ],
            [
                'name' => 'Looking for Alaska',
                'price' => 88000,
                'stock' => 21,
                'description' => 'Miles di boarding school bertemu Alaska.',
                'author' => 'John Green',
                'publisher' => 'Dutton Books',
                'year' => 2005,
                'isbn' => '9780525475064',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/lookingalaska/400/600',
            ],
            [
                'name' => 'The Giver',
                'price' => 75000,
                'stock' => 33,
                'description' => 'Jonas dalam masyarakat utopis yang kelam.',
                'author' => 'Lois Lowry',
                'publisher' => 'Houghton Mifflin',
                'year' => 1993,
                'isbn' => '9780544336261',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/thegiverbook/400/600',
            ],
            [
                'name' => 'Miss Peregrine\'s Home',
                'price' => 102000,
                'stock' => 18,
                'description' => 'Jacob dan anak-anak dengan kemampuan khusus.',
                'author' => 'Ransom Riggs',
                'publisher' => 'Quirk Books',
                'year' => 2011,
                'isbn' => '9781594746031',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/missperegrines/400/600',
            ],
            [
                'name' => 'The Book Thief',
                'price' => 96000,
                'stock' => 22,
                'description' => 'Liesel dan kekuatan kata-kata di Nazi Germany.',
                'author' => 'Markus Zusak',
                'publisher' => 'Knopf Books',
                'year' => 2005,
                'isbn' => '9780375831003',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/bookthief/400/600',
            ],
            [
                'name' => 'Ready Player One',
                'price' => 118000,
                'stock' => 27,
                'description' => 'Wade dalam virtual reality OASIS.',
                'author' => 'Ernest Cline',
                'publisher' => 'Crown Publishers',
                'year' => 2011,
                'isbn' => '9780307887436',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/readyplayerone/400/600',
            ],

            // Self-Help Additional Books (5 more books)
            [
                'name' => '12 Rules for Life',
                'price' => 165000,
                'stock' => 28,
                'description' => 'Antidot untuk kekacauan oleh Jordan Peterson.',
                'author' => 'Jordan B. Peterson',
                'publisher' => 'Random House Canada',
                'year' => 2018,
                'isbn' => '9780345816023',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/12ruleslife/400/600',
            ],
            [
                'name' => 'Grit',
                'price' => 138000,
                'stock' => 31,
                'description' => 'Kekuatan passion dan perseverance.',
                'author' => 'Angela Duckworth',
                'publisher' => 'Scribner',
                'year' => 2016,
                'isbn' => '9781501111112',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/gritbook/400/600',
            ],
            [
                'name' => 'The Four Agreements',
                'price' => 105000,
                'stock' => 26,
                'description' => 'Practical guide untuk kebebasan pribadi.',
                'author' => 'Don Miguel Ruiz',
                'publisher' => 'Amber-Allen Publishing',
                'year' => 1997,
                'isbn' => '9781878424310',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/fouragreements/400/600',
            ],
            [
                'name' => 'Big Magic',
                'price' => 128000,
                'stock' => 23,
                'description' => 'Creative Living Beyond Fear.',
                'author' => 'Elizabeth Gilbert',
                'publisher' => 'Riverhead Books',
                'year' => 2015,
                'isbn' => '9781594634710',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/bigmagic/400/600',
            ],
            [
                'name' => 'Man\'s Search for Meaning',
                'price' => 112000,
                'stock' => 29,
                'description' => 'Pengalaman psikiater di kamp konsentrasi Nazi.',
                'author' => 'Viktor E. Frankl',
                'publisher' => 'Beacon Press',
                'year' => 1946,
                'isbn' => '9780807014295',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/searchmeaning/400/600',
            ],

            // Technology Additional Books (15 more books)
            [
                'name' => 'System Design Interview',
                'price' => 285000,
                'stock' => 22,
                'description' => 'Panduan insider untuk system design interview.',
                'author' => 'Alex Xu',
                'publisher' => 'ByteByteGo',
                'year' => 2020,
                'isbn' => '9798664653403',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/systemdesign/400/600',
            ],
            [
                'name' => 'Cracking the Coding Interview',
                'price' => 295000,
                'stock' => 18,
                'description' => '189 Programming Questions and Solutions.',
                'author' => 'Gayle Laakmann McDowell',
                'publisher' => 'CareerCup',
                'year' => 2015,
                'isbn' => '9780984782857',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/crackingcoding/400/600',
            ],
            [
                'name' => 'Introduction to Algorithms',
                'price' => 450000,
                'stock' => 12,
                'description' => 'Comprehensive guide untuk algoritma komputer.',
                'author' => 'Thomas H. Cormen',
                'publisher' => 'MIT Press',
                'year' => 2009,
                'isbn' => '9780262033848',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/introalgorithms/400/600',
            ],
            [
                'name' => 'Effective Java',
                'price' => 265000,
                'stock' => 16,
                'description' => 'Best practices untuk Java programming.',
                'author' => 'Joshua Bloch',
                'publisher' => 'Addison-Wesley',
                'year' => 2017,
                'isbn' => '9780134685991',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/effectivejava/400/600',
            ],
            [
                'name' => 'You Don\'t Know JS',
                'price' => 185000,
                'stock' => 25,
                'description' => 'Deep dive ke JavaScript language.',
                'author' => 'Kyle Simpson',
                'publisher' => 'O\'Reilly Media',
                'year' => 2014,
                'isbn' => '9781491950357',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/youdontknowjs/400/600',
            ],
            [
                'name' => 'Design Patterns',
                'price' => 310000,
                'stock' => 14,
                'description' => 'Elements of Reusable Object-Oriented Software.',
                'author' => 'Gang of Four',
                'publisher' => 'Addison-Wesley',
                'year' => 1994,
                'isbn' => '9780201633612',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/designpatterns/400/600',
            ],
            [
                'name' => 'The Pragmatic Programmer',
                'price' => 245000,
                'stock' => 19,
                'description' => 'Your journey to mastery, 20th Anniversary Edition.',
                'author' => 'David Thomas & Andrew Hunt',
                'publisher' => 'Addison-Wesley',
                'year' => 2019,
                'isbn' => '9780135957059',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/pragmaticprog/400/600',
            ],
            [
                'name' => 'Clean Code',
                'price' => 225000,
                'stock' => 21,
                'description' => 'Handbook of Agile Software Craftsmanship.',
                'author' => 'Robert C. Martin',
                'publisher' => 'Prentice Hall',
                'year' => 2008,
                'isbn' => '9780132350884',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/cleancode/400/600',
            ],
            [
                'name' => 'Microservices Patterns',
                'price' => 335000,
                'stock' => 13,
                'description' => 'With examples in Java.',
                'author' => 'Chris Richardson',
                'publisher' => 'Manning Publications',
                'year' => 2018,
                'isbn' => '9781617294549',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/microservices/400/600',
            ],
            [
                'name' => 'Building Microservices',
                'price' => 298000,
                'stock' => 17,
                'description' => 'Designing Fine-Grained Systems.',
                'author' => 'Sam Newman',
                'publisher' => 'O\'Reilly Media',
                'year' => 2021,
                'isbn' => '9781492034025',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/buildingmicro/400/600',
            ],
            [
                'name' => 'Domain-Driven Design',
                'price' => 385000,
                'stock' => 11,
                'description' => 'Tackling Complexity in the Heart of Software.',
                'author' => 'Eric Evans',
                'publisher' => 'Addison-Wesley',
                'year' => 2003,
                'isbn' => '9780321125217',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/ddd/400/600',
            ],
            [
                'name' => 'Kubernetes in Action',
                'price' => 315000,
                'stock' => 15,
                'description' => 'Comprehensive guide untuk Kubernetes.',
                'author' => 'Marko Lukša',
                'publisher' => 'Manning Publications',
                'year' => 2017,
                'isbn' => '9781617293726',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/kubernetes/400/600',
            ],
            [
                'name' => 'Hands-On Machine Learning',
                'price' => 365000,
                'stock' => 13,
                'description' => 'With Scikit-Learn, Keras, and TensorFlow.',
                'author' => 'Aurélien Géron',
                'publisher' => 'O\'Reilly Media',
                'year' => 2019,
                'isbn' => '9781492032649',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/handsonml/400/600',
            ],
            [
                'name' => 'Python Crash Course',
                'price' => 195000,
                'stock' => 24,
                'description' => 'A Hands-On, Project-Based Introduction to Programming.',
                'author' => 'Eric Matthes',
                'publisher' => 'No Starch Press',
                'year' => 2019,
                'isbn' => '9781593279288',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/pythoncrash/400/600',
            ],
            [
                'name' => 'Head First Design Patterns',
                'price' => 275000,
                'stock' => 18,
                'description' => 'Brain-Friendly Guide untuk Design Patterns.',
                'author' => 'Eric Freeman & Elisabeth Robson',
                'publisher' => 'O\'Reilly Media',
                'year' => 2020,
                'isbn' => '9781492078005',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/headfirstdesign/400/600',
            ],
            [
                'name' => 'Rascal Does Not Dream of Bunny Girl Senpai Vol. 1',
                'price' => 65000,
                'stock' => 5,
                'description' => 'Siapakah gadis itu? Kenapa hanya Sakuta yang dapat melihatnya?',
                'author' => 'Hajime Kamoshida',
                'publisher' => 'ASCII Media Works',
                'year' => 2014,
                'isbn' => '9784048664875',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/headfirstdesign/400/600',
            ],

        ];

        foreach ($books as $data) {
            // Upsert berbasis ISBN agar idempotent (tidak dobel saat seed ulang)
            Book::updateOrCreate(
                ['isbn' => $data['isbn']],
                $data
            );
        }
    }
}
