<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            // Fiction (category_id:1) - Total 7 Buku
            [
                'name' => 'The Little Prince',
                'price' => 150000,
                'stock' => 25,
                'description' => 'Cerita klasik seorang pangeran kecil menjelajah alam.',
                'author' => 'Antoine de Saint-Exupéry',
                'publisher' => 'Reynal & Hitchcock',
                'year' => 1943,
                'isbn' => '9780156012195',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/littleprincecover/400/600', 
            ],
            [
                'name' => 'Laskar Pelangi',
                'price' => 85000,
                'stock' => 30,
                'description' => 'Perjuangan anak-anak Belitung mengejar pendidikan.',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'year' => 2005,
                'isbn' => '9789793062794',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/laskarpelangi/400/600',
            ],
            [
                'name' => 'To Kill a Mockingbird',
                'price' => 99000,
                'stock' => 28,
                'description' => 'Klasik tentang keadilan dan moral di Selatan Amerika.',
                'author' => 'Harper Lee',
                'publisher' => 'J.B. Lippincott & Co.',
                'year' => 1960,
                'isbn' => '9780061120084',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/mockingbirdbook/400/600',
            ],
            [
                'name' => '1984',
                'price' => 88000,
                'stock' => 34,
                'description' => 'Dystopia totalitarian pengawasan penuh.',
                'author' => 'George Orwell',
                'publisher' => 'Secker & Warburg',
                'year' => 1949,
                'isbn' => '9780451524935',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/orwell1984/400/600',
            ],
            [
                'name' => 'The Hobbit',
                'price' => 110000,
                'stock' => 22,
                'description' => 'Petualangan Bilbo Baggins sebelum Lord of the Rings.',
                'author' => 'J.R.R. Tolkien',
                'publisher' => 'George Allen & Unwin',
                'year' => 1937,
                'isbn' => '9780547928227',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/thehobbit/400/600',
            ],
            [ // Buku Baru 1
                'name' => 'Harry Potter and the Sorcerer\'s Stone',
                'price' => 175000,
                'stock' => 30,
                'description' => 'Awal kisah petualangan penyihir muda Harry Potter.',
                'author' => 'J.K. Rowling',
                'publisher' => 'Bloomsbury Publishing',
                'year' => 1997,
                'isbn' => '9780747532743',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/harrypotter1/400/600',
            ],
            [ // Buku Baru 2
                'name' => 'The Da Vinci Code',
                'price' => 130000,
                'stock' => 20,
                'description' => 'Thriller misteri yang melibatkan simbol rahasia dan sejarah agama.',
                'author' => 'Dan Brown',
                'publisher' => 'Doubleday',
                'year' => 2003,
                'isbn' => '9780385504201',
                'category_id' => 1,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/davincicode/400/600',
            ],

            // Non-Fiction (category_id:2) - Total 7 Buku
            [
                'name' => 'Sapiens',
                'price' => 180000,
                'stock' => 20,
                'description' => 'Sejarah singkat umat manusia.',
                'author' => 'Yuval Noah Harari',
                'publisher' => 'Harper',
                'year' => 2014,
                'isbn' => '9780062316097',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/sapiensbook/400/600',
            ],
            [
                'name' => 'Atomic Habits',
                'price' => 165000,
                'stock' => 35,
                'description' => 'Membentuk kebiasaan baik & hilangkan kebiasaan buruk.',
                'author' => 'James Clear',
                'publisher' => 'Avery',
                'year' => 2018,
                'isbn' => '9780735211292',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/atomichabits/400/600',
            ],
            [
                'name' => 'Educated',
                'price' => 135000,
                'stock' => 18,
                'description' => 'Memoar perjalanan dari keluarga survivalist ke akademis.',
                'author' => 'Tara Westover',
                'publisher' => 'Random House',
                'year' => 2018,
                'isbn' => '9780399590504',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/educatedbook/400/600',
            ],
            [
                'name' => 'Thinking, Fast and Slow',
                'price' => 150000,
                'stock' => 26,
                'description' => 'Dua sistem berpikir: cepat intuitif dan lambat analitis.',
                'author' => 'Daniel Kahneman',
                'publisher' => 'Farrar, Straus and Giroux',
                'year' => 2011,
                'isbn' => '9780374533557',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/fastslowbook/400/600',
            ],
            [
                'name' => 'Deep Work',
                'price' => 125000,
                'stock' => 30,
                'description' => 'Strategi fokus mendalam untuk hasil maksimal.',
                'author' => 'Cal Newport',
                'publisher' => 'Grand Central Publishing',
                'year' => 2016,
                'isbn' => '9781455586691',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/deepworkbook/400/600',
            ],
            [ // Buku Baru 1
                'name' => 'The Power of Now',
                'price' => 115000,
                'stock' => 25,
                'description' => 'Panduan untuk hidup di masa kini dan menemukan kedamaian.',
                'author' => 'Eckhart Tolle',
                'publisher' => 'New World Library',
                'year' => 1997,
                'isbn' => '9781577314806',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/powerofnow/400/600',
            ],
            [ // Buku Baru 2
                'name' => 'Slightly Better Than Average: An Autobiography',
                'price' => 95000,
                'stock' => 15,
                'description' => 'Kisah inspiratif tentang perjuangan hidup dan karir.',
                'author' => 'Ernest Prakasa',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2015,
                'isbn' => '9786020317544',
                'category_id' => 2,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/ernestautobiography/400/600',
            ],

            // Comic & Manga (category_id:3) - Total 5 Buku
            [
                'name' => 'One Piece Vol. 1',
                'price' => 45000,
                'stock' => 50,
                'description' => 'Awal petualangan Luffy mencari One Piece.',
                'author' => 'Eiichiro Oda',
                'publisher' => 'Shueisha',
                'year' => 1997,
                'isbn' => '9784088725095',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/onepiecemanga/400/600',
            ],
            [
                'name' => 'Naruto Vol. 1',
                'price' => 42000,
                'stock' => 40,
                'description' => 'Perjalanan ninja muda Naruto.',
                'author' => 'Masashi Kishimoto',
                'publisher' => 'Shueisha',
                'year' => 1999,
                'isbn' => '9784088730226',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/narutomanga/400/600',
            ],
            [
                'name' => 'Demon Slayer Vol. 1',
                'price' => 52000,
                'stock' => 38,
                'description' => 'Awal perjalanan Tanjiro melawan iblis.',
                'author' => 'Koyoharu Gotouge',
                'publisher' => 'Shueisha',
                'year' => 2016,
                'isbn' => '9781974700523',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/demonslayer/400/600',
            ],
            [
                'name' => 'Chainsaw Man Vol. 1',
                'price' => 54000,
                'stock' => 32,
                'description' => 'Denji bergabung dengan pemburu iblis pemerintah.',
                'author' => 'Tatsuki Fujimoto',
                'publisher' => 'Shueisha',
                'year' => 2019,
                'isbn' => '9781974709939',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/chainsawman/400/600',
            ],
            [
                'name' => 'Spy x Family Vol. 1',
                'price' => 56000,
                'stock' => 29,
                'description' => 'Keluarga pura-pura penuh rahasia unik.',
                'author' => 'Tatsuya Endo',
                'publisher' => 'Shueisha',
                'year' => 2020,
                'isbn' => '9781974715466',
                'category_id' => 3,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/spyxfamily/400/600',
            ],
            
            // Teen Reading (category_id:4) - Total 5 Buku
            [
                'name' => 'The Hunger Games',
                'price' => 120000,
                'stock' => 27,
                'description' => 'Pertarungan hidup dan kemerdekaan di Capitol.',
                'author' => 'Suzanne Collins',
                'publisher' => 'Scholastic',
                'year' => 2008,
                'isbn' => '9780439023528',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/hungergamesbook/400/600',
            ],
            [
                'name' => 'Divergent',
                'price' => 98000,
                'stock' => 24,
                'description' => 'Fraksi dan identitas dalam masyarakat terpecah.',
                'author' => 'Veronica Roth',
                'publisher' => 'Katherine Tegen Books',
                'year' => 2011,
                'isbn' => '9780062024039',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/divergentbook/400/600',
            ],
            [
                'name' => 'The Maze Runner',
                'price' => 97000,
                'stock' => 31,
                'description' => 'Remaja terjebak dalam labirin misterius.',
                'author' => 'James Dashner',
                'publisher' => 'Delacorte Press',
                'year' => 2009,
                'isbn' => '9780385737951',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/mazerunnerbook/400/600',
            ],
            [ // Buku Baru 1
                'name' => 'Percy Jackson & The Lightning Thief',
                'price' => 115000,
                'stock' => 28,
                'description' => 'Petualangan Percy Jackson menemukan petir Zeus yang hilang.',
                'author' => 'Rick Riordan',
                'publisher' => 'Disney Hyperion',
                'year' => 2005,
                'isbn' => '9780786856299',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/percyjackson1/400/600',
            ],
            [ // Buku Baru 2
                'name' => 'The Fault in Our Stars',
                'price' => 105000,
                'stock' => 25,
                'description' => 'Kisah cinta remaja yang menyentuh di tengah penyakit.',
                'author' => 'John Green',
                'publisher' => 'Dutton Books',
                'year' => 2012,
                'isbn' => '9780525478812',
                'category_id' => 4,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/faultinourstars/400/600',
            ],
            
            // Self-Help (category_id:5) - Total 6 Buku
            [
                'name' => 'The Subtle Art of Not Giving a F*ck',
                'price' => 140000,
                'stock' => 33,
                'description' => 'Prioritaskan hal penting dalam hidup.',
                'author' => 'Mark Manson',
                'publisher' => 'HarperOne',
                'year' => 2016,
                'isbn' => '9780062457714',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/subtleartbook/400/600',
            ],
            [
                'name' => 'The Power of Habit',
                'price' => 132000,
                'stock' => 29,
                'description' => 'Bagaimana kebiasaan bekerja dan diubah.',
                'author' => 'Charles Duhigg',
                'publisher' => 'Random House',
                'year' => 2012,
                'isbn' => '9780812981605',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/powerofhabitbook/400/600',
            ],
            [
                'name' => 'Can\'t Hurt Me',
                'price' => 155000,
                'stock' => 21,
                'description' => 'Mental toughness dan disiplin radikal.',
                'author' => 'David Goggins',
                'publisher' => 'Lioncrest Publishing',
                'year' => 2018,
                'isbn' => '9781544512273',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/canthurtmebook/400/600',
            ],
            [ // Buku Baru 1
                'name' => 'Dare to Lead',
                'price' => 145000,
                'stock' => 24,
                'description' => 'Belajar memimpin dengan keberanian, empati, dan koneksi.',
                'author' => 'Brené Brown',
                'publisher' => 'Random House',
                'year' => 2018,
                'isbn' => '9780399592522',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/daretolead/400/600',
            ],
            [ // Buku Baru 2
                'name' => 'Filosofi Teras',
                'price' => 95000,
                'stock' => 35,
                'description' => 'Panduan praktis filosofi Stoa untuk mengatasi emosi negatif.',
                'author' => 'Henry Manampiring',
                'publisher' => 'Kompas',
                'year' => 2018,
                'isbn' => '9786024125189',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/filosofiteras/400/600',
            ],
            [ // Buku Baru 3
                'name' => 'Start With Why',
                'price' => 160000,
                'stock' => 20,
                'description' => 'Bagaimana pemimpin hebat menginspirasi tindakan.',
                'author' => 'Simon Sinek',
                'publisher' => 'Portfolio',
                'year' => 2009,
                'isbn' => '9781591846444',
                'category_id' => 5,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/startwithwhy/400/600',
            ],

            // Technology (category_id:6) - Total 5 Buku
            [
                'name' => 'Clean Architecture',
                'price' => 230000,
                'stock' => 20,
                'description' => 'Struktur arsitektur perangkat lunak yang maintainable.',
                'author' => 'Robert C. Martin',
                'publisher' => 'Prentice Hall',
                'year' => 2017,
                'isbn' => '9780134494166',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/cleanarchitecturebook/400/600',
            ],
            [
                'name' => 'Designing Data-Intensive Applications',
                'price' => 350000,
                'stock' => 15,
                'description' => 'Fundamental sistem data modern skala besar.',
                'author' => 'Martin Kleppmann',
                'publisher' => 'O\'Reilly Media',
                'year' => 2017,
                'isbn' => '9781449373320',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/ddiabook/400/600',
            ],
            [
                'name' => 'Refactoring',
                'price' => 275000,
                'stock' => 19,
                'description' => 'Pola peningkatan kualitas kode tanpa mengubah perilaku.',
                'author' => 'Martin Fowler',
                'publisher' => 'Addison-Wesley',
                'year' => 2018,
                'isbn' => '9780134757599',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/refactoringbook/400/600',
            ],
            [ // Buku Baru 1
                'name' => 'The Mythical Man-Month',
                'price' => 190000,
                'stock' => 17,
                'description' => 'Esai tentang rekayasa perangkat lunak.',
                'author' => 'Frederick Brooks Jr.',
                'publisher' => 'Addison-Wesley',
                'year' => 1975,
                'isbn' => '9780201835953',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/mythicalmanmonth/400/600',
            ],
            [ // Buku Baru 2
                'name' => 'Code Complete',
                'price' => 320000,
                'stock' => 14,
                'description' => 'Panduan komprehensif untuk konstruksi perangkat lunak.',
                'author' => 'Steve McConnell',
                'publisher' => 'Microsoft Press',
                'year' => 2004,
                'isbn' => '9780735619678',
                'category_id' => 6,
                'is_active' => true,
                'cover_image' => 'https://picsum.photos/seed/codecomplete/400/600',
            ],

        ];

        foreach ($books as $data) {
            // Upsert berbasis ISBN agar idempotent (tidak dobel saat seed ulang)
            Book::updateOrCreate(
                ['isbn' => $data['isbn']],
                $data
            );
        }
    }
}